# 电池电量报告间隔时间单位是秒
# 배터리 잔량 보고 주기 (단위: 초)
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# 배터리 서비스 활성화 및 보고 설정
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y

# 분리형(Split) 키보드 왼쪽/오른쪽 배터리 수집 및 전달 설정
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# 增加键盘消抖
# 키보드 디바운스 시간 증가 (키 중복입력 방지)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# 增加键盘的 BLE 无线电的发射功率，用解决延迟和左右通讯不佳的问题
# BLE 송신 전력 증가 (지연 및 좌우 연결 불안정 문제 해결용)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 更改键盘默认显示名称
# 키보드 디바이스 이름 설정
CONFIG_ZMK_KEYBOARD_NAME="Lily58"

# 用于解决 Windows 中与电池报告相关的错误
# Windows에서 배터리 정보 관련 오류 해결용 설정
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# oled相关配置
# OLED 관련 설정
CONFIG_ZMK_DISPLAY=y
#CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=n

# Enable a widget to show words per minute
# 타자 속도(WPM) 위젯 사용 여부
#CONFIG_ZMK_WIDGET_WPM_STATUS=n
#CONFIG_ZMK_WIDGET_LAYER_STATUS=n
#CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=n

#Bongo cat猫猫敲键盘动画
# Bongo Cat 애니메이션 표시 여부
#CONFIG_ZMK_WIDGET_BONGO_CAT=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

#休眠相关配置
# 절전 모드 관련 설정
# Milliseconds of inactivity before entering idle state	(10 minute)
CONFIG_ZMK_IDLE_TIMEOUT=600000

# Enable deep sleep support	
CONFIG_ZMK_SLEEP=y

# Milliseconds of inactivity before entering deep sleep (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# zmk studio相关配置
# ZMK Studio 관련 설정
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

#rgb相关配置
# RGB 관련 설정
CONFIG_ZMK_RGB_UNDERGLOW=y # RGB 언더글로우 기능 사용
CONFIG_WS2812_HAS_DRIVER=y # WS2812 LED 스트립 사용

# 부팅 시 RGB를 꺼진 상태로 시작
CONFIG_ZMK_RGB_UNDERGLOW_DEFAULT_ON=n # 꺼진 상태로 부팅
CONFIG_ZMK_RGB_UNDERGLOW_DEFAULT_VAL=0

#键盘进入空闲状态时关闭RGB
# 키보드가 유휴 상태일 때 RGB 자동 꺼짐
CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n # 외부 전원이 연결되었을 때 RGB 유지 여부 (n이면 유지 안 함)
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3 # 부팅 시 RGB 효과 시작값 (3번 효과부터 시작)
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60 # 최대 밝기 제한 (60/255)

#旋钮配置
# 인코더(회전 노브) 설정
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
